name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses & install platforms/build-tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Download Gradle 8.6 and generate wrapper
        run: |
          curl -sLo gradle.zip https://services.gradle.org/distributions/gradle-8.6-bin.zip
          unzip -q gradle.zip
          ./gradle-8.6/bin/gradle wrapper
          chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --stacktrace --info

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
